Update package build for noble and rocky10 as well as py3.12

diff --git a/packages/st2/Makefile b/packages/st2/Makefile
--- a/packages/st2/Makefile
+++ b/packages/st2/Makefile
@@ -1,38 +1,43 @@
+SHELL = /bin/bash
 WHEELDIR ?= /tmp/wheelhouse
 ST2_COMPONENT := $(notdir $(CURDIR))
 ST2PKG_RELEASE ?= 1
 CHANGELOG_COMMENT ?= "automated build, version: $(ST2PKG_VERSION)"
 
-ifneq (,$(wildcard /etc/debian_version))
-	DEBIAN := 1
-	#DEB_EPOCH := $(shell echo $(ST2PKG_VERSION) | grep -q dev || echo '1')
-	DEB_DISTRO := $(shell lsb_release -cs)
-else ifneq (,$(wildcard /etc/rocky-release))
-	EL_DISTRO:=rocky
-	EL_VERSION := $(shell cat /etc/rocky-release | grep -oP '(?<= )[0-9]+(?=\.)')
-	REDHAT := 1
-else ifneq (,$(wildcard /etc/redhat-release))
-	EL_DISTRO:=redhat
-	EL_VERSION := $(shell cat /etc/redhat-release | grep -oP '(?<= )[0-9]+(?=\.)')
-	REDHAT := 1
-else
-	REDHAT := 1
-	DEB_DISTRO := unstable
-endif
+OS_ID := $(shell source /etc/os-release; echo $$ID)
+# Major OS version is sufficient.
+OS_VERSION := $(shell source /etc/os-release; echo $${VERSION_ID%.*})
 
-PYTHON_BINARY := /usr/bin/python3
-PIP_BINARY := pip3
-PYTHON_ALT_BINARY := python3
+PYBIN := python3
+PIPBIN := pip3
+
+ifeq ($(OS_ID),rocky)
+	EL_VERSION := $(OS_VERSION)
+	# Rocky9 requires py3.11 instead of default py3.9 interpreter.
+	ifeq ($(OS_VERSION),9)
+		PYBIN = python3.11
+		PIPBIN := pip3.11
+	endif
+else ifeq ($(OS_ID),rhel)
+	EL_VERSION := $(OS_VERSION)
+else ifeq ($(OS_ID),ubuntu)
+	DEB_DISTRO := $(shell source /etc/os-release; echo $$VERSION_CODENAME)
+else ifeq ($(OS_ID),debian)
+	DEB_DISTRO := $(shell source /etc/os-release; echo $$VERSION_CODENAME)
+else
+	echo "$(OS_ID) is not supported."
+	exit 1
+endif
 
 RUNNERS := $(shell ls ../contrib/runners)
 
 # Moved from top of file to handle when only py2 or py3 available
-ST2PKG_VERSION ?= $(shell $(PYTHON_BINARY) -c "from $(ST2_COMPONENT) import __version__; print(__version__),")
+ST2PKG_VERSION ?= $(shell $(PYBIN) -c "from $(ST2_COMPONENT) import __version__; print(__version__),")
 
 # Note: We dynamically obtain the version, this is required because dev
 # build versions don't store correct version identifier in __init__.py
 # and we need setup.py to normalize it (e.g. 1.4dev -> 1.4.dev0)
-ST2PKG_NORMALIZED_VERSION ?= $(shell $(PYTHON_BINARY) setup.py --version || echo "failed_to_retrieve_version")
+ST2PKG_NORMALIZED_VERSION ?= $(shell $(PYBIN) setup.py --version || echo "failed_to_retrieve_version")
 
 # Makefile function to retry the failed command 'N' times
 # Make sure you use it for nothing but networking stuff (think about race conditons)
@@ -44,13 +49,14 @@ all: info install
 
 .PHONY: info
 info:
-	@echo "DEBIAN=$(DEBIAN)"
-	@echo "REDHAT=$(REDHAT)"
 	@echo "EL_DISTRO=$(EL_DISTRO)"
 	@echo "EL_VERSION=$(EL_VERSION)"
 	@echo "DEB_DISTRO=$(DEB_DISTRO)"
-	@echo "PYTHON_BINARY=$(PYTHON_BINARY)"
-	@echo "PIP_BINARY=$(PIP_BINARY)"
+	@echo "PYBIN=$(PYBIN)"
+	@$(PYBIN) --version
+	@echo "PIPBIN=$(PIPBIN)"
+	@$(PIPBIN) --version
+
 
 install: wheelhouse changelog
 
@@ -90,9 +96,7 @@ post_install:
 	sed -i -r "/args\s*=\s*/s%logs%/var/log/st2%g" $(DESTDIR)/etc/st2/logging.*conf
 	sed -i "/\[logger_root\]/,/\[.*\]\|\s*$$/ {s/level=DEBUG/level=INFO/}" $(DESTDIR)/etc/st2/logging.*conf
 	sed -i "/\[logger_root\]/,/\[.*\]\|\s*$$/ {s/level=DEBUG/level=INFO/}" $(DESTDIR)/etc/st2/syslog.*conf
-ifeq ($(REDHAT),1)
-	if [[ `$(PYTHON_ALT_BINARY) /root/scripts/platform_major_version.py` = 8 ]]; then sed -i -r 's/virtualenv_opts\s*=.*/virtualenv_opts =/' $(DESTDIR)/etc/st2/st2.conf; fi
-endif
+
 
 populate_version: .stamp-populate_version
 .stamp-populate_version:
@@ -101,11 +105,11 @@ populate_version: .stamp-populate_version
 	touch $@
 
 requirements:
-	$(PYTHON_BINARY) ../scripts/fixate-requirements.py -s ../st2*/in-requirements.txt ../contrib/runners/*/in-requirements.txt -f ../fixed-requirements.txt
+	$(PYBIN) ../scripts/fixate-requirements.py -s ../st2*/in-requirements.txt ../contrib/runners/*/in-requirements.txt -f ../fixed-requirements.txt
 	cat requirements.txt
 
 changelog: populate_version
-ifeq ($(DEBIAN),1)
+ifdef DEB_DISTRO
 	[ -z "$(DEB_EPOCH)" ] && _epoch="" || _epoch="$(DEB_EPOCH):"; \
 		dch -m --force-distribution -v$${_epoch}$(ST2PKG_VERSION)-$(ST2PKG_RELEASE) -D$(DEB_DISTRO) $(CHANGELOG_COMMENT)
 endif
@@ -114,8 +118,8 @@ wheelhouse: .build-runners .stamp-wheelhouse
 .stamp-wheelhouse: | populate_version requirements inject-deps
 	cat requirements.txt
 	# Try to install wheels 2x in case the first one fails
-	$(PIP_BINARY) --use-deprecated=legacy-resolver  wheel --wheel-dir=$(WHEELDIR) --find-links=$(WHEELDIR) -r requirements.txt || \
-		$(PIP_BINARY) --use-deprecated=legacy-resolver wheel --wheel-dir=$(WHEELDIR) --find-links=$(WHEELDIR) -r requirements.txt
+	$(PIPBIN) wheel --wheel-dir=$(WHEELDIR) --find-links=$(WHEELDIR) -r requirements.txt || \
+	$(PIPBIN) wheel --wheel-dir=$(WHEELDIR) --find-links=$(WHEELDIR) -r requirements.txt
 	touch $@
 
 .build-runners:
@@ -125,7 +129,7 @@ wheelhouse: .build-runners .stamp-wheelhouse
 	@echo $(RUNNERS)
 	@for runner in $(RUNNERS); do \
 		echo "Installing $$runner"; \
-		$(PIP_BINARY) wheel --wheel-dir=$(WHEELDIR) --find-links=$(WHEELDIR) -r ../contrib/runners/$$runner/requirements.txt ../contrib/runners/$$runner; \
+		$(PIPBIN) wheel --wheel-dir=$(WHEELDIR) --find-links=$(WHEELDIR) -r ../contrib/runners/$$runner/requirements.txt ../contrib/runners/$$runner; \
 	done
 	touch $@
 
